# Generated by Django 5.2.4 on 2025-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=50)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "barcode_image",
                    models.ImageField(blank=True, null=True, upload_to="barcodes/"),
                ),
            ],
        ),
    ]
