services:
  - type: web
    name: student-barcode-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crud.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crud.settings
      - key: PYTHON_VERSION
        value: 3.11
